# these are some videos, we will add the entire collection later

TARGET_DIR=/tmp/videos

cd ${TARGET_DIR}
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=nZQQUShfdEs'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=a1D6xizxLXg'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=TN-pwblNxU4'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=tO01J-M3g0U'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=hVzL48VgYZQ'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=SMwxZO2UjBw'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=QPdWJeybMo8'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=a1D6xizxLXg'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=nZQQUShfdEs'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=4Epudzs5GYo'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=sLprVF6d7Ug'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=8ZEriMtypas'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=SsbYwtLLgwM'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=A8s7dh_SJHQ'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=mkggXE5e2yk'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=o_24LPjOIHI'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=Z-BaOvkkIfc'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=o_24LPjOIHI'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=hvj4GePMEnU'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=l_-gNiiKeIU'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=9KBwSA6tgeo'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=mvfdGJVjLto'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=SYNjDs1PR9c'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=w2H07DRv2_M'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=IlXhywbggFY'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=fbumPrvwWmo'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=nCWqPa20kmY'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=I7ZRseJlZS4'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=Jjhyboay6y0'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=Z6lYqgWAmrg&t=4s'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=WA3JT3nRGU8'
youtube-dl -f bestvideo 'https://www.youtube.com/watch?v=9ge2gx69ftk'
youtube-dl -f bestvideo 'https://www.youtube.com/playlist?list=PLD33E5618740295DF'
youtube-dl -f bestvideo 'https://www.youtube.com/playlist?list=PL-NzkgWzAqPzErfdIWhmMV5l7vkG2nfOz'
youtube-dl -f bestvideo 'https://www.youtube.com/playlist?list=PL-NzkgWzAqPyR6LO8oR-JBdebcOwva_7h'